// constants/filters.ts
export const DEFAULT_COMPANY = "figma";
export const COMPANIES = [
    "figma",
    "airbnb",
    "discord",
    "stripe",
    "openai",
    "github",
    "notion",
    "dropbox",
    "doordash",
    "robinhood",
    "coursera",
    "gusto",
    "asana",
    "loom",
    "ramp",
    "atlassian",
    "datadog",
    "snapchat",
    "twitch",
    "unity",
    "intercom",
    "clickup",
    "cruise",
    "brex",
    "niantic",
    "postman",
    "coinbase",
    "affirm",
    "gem",
    "instacart",
    "hellofresh",
    "klaviyo",
    "uber",
    "reddit",
    "attentive",
    "grubhub",
    "quip",
    "wise",
    "monday",
    "cloudflare",
    "okta",
    "squarespace",
    "zendesk"
  ];
  